# Generated by Django 3.1.7 on 2022-03-12 08:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
                ('cover_image', models.FileField(default='channel-banner.png', upload_to='profile_pics')),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('url', models.CharField(blank=True, max_length=80, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('bio', models.TextField(default='be the change u want to see in the world', max_length=300)),
                ('about', models.TextField(default='welcome to branagram!', max_length=500)),
                ('favorites', models.ManyToManyField(to='blog.Post')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blacklisters', models.ManyToManyField(related_name='blocker_users', to=settings.AUTH_USER_MODEL)),
                ('blacklists', models.ManyToManyField(related_name='blocked_users', to=settings.AUTH_USER_MODEL)),
                ('current_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('follower', models.ManyToManyField(related_name='follow', to=settings.AUTH_USER_MODEL)),
                ('following', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
